### ISSUE TITLE
Truly decentralized domain names

### ISSUE THREAD

**Issue by brechtcs** [datprotocol/dat-dns#6]
Following [our discussion](https://github.com/datprotocol/dat-dns/issues/5) about `.local` domains, I've started thinking about the ideal design for domain names in the dat ecosystem overall. While DNS-over-HTTPS is a good solution for backwards compatibility with the existing DNS system, I don't think that it is the long-term answer to this problem. It doesn't solve the fundamental problems of centralised DNS, i.e. the scarcity of good names and the resulting domain squatting.

Instead I think there's a solution that is as secure as DNS-over-HTTPS, as well as truly decentralised. It's a system I like to think of as "dat addressbooks".

A dat addressbook would itself just be a dat, with in it plain text files structured like the current `.well-known/dat` responses. A client could then subscribe to one or more of these addressbooks, and **assign them to a TLD of their choice**. For example, an addressbook of the Beaker organisation could be a dat with the following files:

```
dat.json
browser.txt
paul.txt
tara.txt
```

As a user I could then decide to subscribe to this adressbook and map it to the `.beaker` TLD. Then when I request `dat://browser.beaker`, dat would use the record in the `browser.txt` file to resolve the domain. In this model we could allow an addressbook to specify a preferred TLD in its `dat.json` file, but it is crucial that the user can override this suggestion. **This way the end user has the power/responsibility to resolve possible domain name collisions.** This makes it fully decentralized, because the user has the final say, but also secure, because the dat protocol guarantees that no third party can tamper with these addressbooks.

Going back to the Beaker example, let's say a user has already mapped the `.beaker` TLD to an addressbook with sites selling laboratory equipment, but wants to subscribe to the Beaker Browser one too. To resolve this they could just choose to map that one to `.beakerbrowser`.

To support this, I think the API for `dat-dns` would just need an extra option to pass in an object containing addressbooks of this format:

```js
var addressbooks = {
    <tld>: <dat-url>, 
    // more addressbook mappings
} 
```

I'll try to spend some time to hack together a proof of concept, and if the [dat working group](https://github.com/datprotocol/working-group) is on board with this idea I'd be more than happy to write a formal spec.

**Comment by pfrazee** [comment]
Tara and I spent a lot of time investigating this idea. The problem we hit was that if there is not a universal mapping within a computing group -- and in the case of browsers, that computing group is the world -- then you introduce ambiguity in URL resolution which is extremely hard to diagnose and solve. Without shared configuration, links will fail and there will be no information available to solve the issue.

**Comment by brechtpm** [comment]
Right, but I think that's that's more a UX problem than a technical one. Right now we expect our DNS system to do two jobs:

1. Provide a human-readable layer on top of IP addresses
2. Give a permanent address to an underlying resource that could move to a different IP

In `dat` we technically don't need (2) anymore, as the public key already provides a permanent address for the shared resource. So in theory, any dat based domain name system can fully focus on solving (1), which I think the addressbook proposal does better than traditional DNS.

You're right though that there is a problem putting this in practice. People are now used to the fact that the human-readable domain is also the thing they can use to create a hyperlink. In this system though, there is a diffence between the address you type in the statusbar, and the address you should send to a friend. Making sure people do this right is indeed a tricky problem to solve.

**Comment by pfrazee** [comment]
I'm not sure it's useful to dissociate the UX from the technical elements here. The technical work is trivial, it's the UX that's hard. Part of me agrees that we could lay the foundation and just let users figure it out, but the other part of me knows that any core feature is an obligation. 

As a tool for friend-groups and offices to share more conveniently, shared host-files make a lot of sense. As a tool for global sharing, it would create a lot of problems. Should we let the latter stop us from the former? I should also note that smaller computing groups will need to manually coordinate with each other to get their TLD assignments right. If you set my address book to `pfrazee` and I set it to `paul` then when I share `home.paul` you're going to get a 404.

I'm not wholly against this! I'm just wary of diving into something that could cause trouble. Perhaps we explore it as an experimental and unadvertised feature in Beaker, cc @taravancil wdyt

**Comment by paul90** [comment]
_Saw this issue reference in chat a few days ago, some thoughts which may, or may not, be helpful._

If names are not globally unique, a possible approach to take is that they have a meaning only within the context they are being used. When possible ambiguity arises, such as when typing it into the URL bar, the user's address book (and any linked address books) could be searched and results presented, together the context in which they were found, to allow an informed choice to be made (example below).

> If you set my address book to `pfrazee` and I set it to `paul` then when I share `home.paul` you're going to get a 404.

I would have thought that the resolution process still find `home.paul` in your linked address book?

If I also have a `home.paul` in my address book, and Brecht set my address book to `paul90` then when searching for `home.paul` it will found within the context of two linked address books. The disambiguation could offer both `pfrazee` or `paul90` variants of `home.paul` for a choice to be made. This can't be achieved if the user can't give the link to external address book a name that is meaningful to them.

It is probably not unreasonable if when I use a name when creating a link that the name exists in my address book. Though it might be nice if I could an alias pointing to an entry in another address book e.g. I might create `home.pfazee` as an alias to `home.paul` in your address book. _At this point I start wondering if user DNS terminology such as `domain` is not just a potential source of confusion, and how DNS and decentralized names are told apart._

I might not be unreasonable for any dat that contains links using decentralized names to have either a link to an address book or maybe its own address book. So carrying the context the name was used in with them, and allowing name resolution to be achieved consistently.

**Comment by brechtpm** [comment]
Right @paul90, that's exactly why I do see the UX as a separate problem from the technical one.

Basically, I think in this package we should only decide whether the proposed address book format is a secure way to transmit and resolve DNS records.

If we decide to do that, then I think the next step after that is to use it in higher level applications like Beaker in a way that makes sense to people. This higher level implementation could still diverge heavily from my original proposal. For example we could decide to only accept addressbooks from recognised DNS providers, rather than the free-for-all I'm dreaming of :D

In this alternative model adding custom dat addressbooks would be advanced level configuration on par with people customising their hostfiles right now.

So putting the UX decision aside for a second, I think the basic implication for this package still stands: distributing DNS records through dat addressbooks is more decentralised and robust than unicast DNS, and as far as I understand just as secure. That's why I believe we know enough already to support it in this package.

As I said in the original issue, I'm willing to work on this myself if everyone agrees this is a good idea.

**Comment by brechtpm** [comment]
Oops, just realised I forgot to reply to @paul90's original point. I do agree that having dat sites include the necessary DNS information for outgoing links is a great idea.

The one thing that isn't solved by such an approach, is a way to link these domains outside of the dat ecosystem (i.e. email, chat, etc.). I'm not sure how to solve this yet either. But the point I was trying to make in my last post is that I don't think all these higher level problems have to be solved before settling on the lower level implementation (which should be pretty straightforward, as @pfrazee has noted).

**Comment by pfrazee** [comment]
I'm OK with a PR to this module that adds support for manual mappings, perhaps by an optional `async` callback. No reason not to. Protocols for shared addressbooks could then be implemented downstream. Something like:

```js
const datDns = require('dat-dns')({
  async lookup (name) {
    // do manual lookup here
    // eg... `return await mydb.get(name)`
    // or... `return myBook[name]`
  }
})
```

If you're interested in taking social dns further, I'd suggest writing a proposal on the UX. We need to answer:

 - How would users be told about custom mappings? (How is it described? What are they told that social DNS solves? Which kinds of users are expected to use it? Is mastery necessary in order to participate in the Dat-Web?)
 - How would they add new TLDs? (How much primacy is the tool given? Are users expected to add new TLDs often?)
 - How would they share their own TLD? (Is your ability to publish severely limited by not having a lot of "subscribers" to your TLD? Do you need to change what you share based on whether you think your audience "subscribes?")
 - How would they add mappings to their own TLD? (Again, how much primacy is the tool given? Are users expected to add mappings to their TLD often?)
